### ISSUE TITLE
Header is not generated if it is missing but git-state-hash is present

### ISSUE THREAD

**Issue by jakebott** [andrew-hardin/cmake-git-version-tracking#9] opened 2020-02-04 01:17 UTC
If the generated header file goes missing but the git-state-hash is not also deleted (for example if `make clean` is run), the header file will not be generated again, causing compilation to fail.

Example steps to reproduce using hello-world demo:
```bash
cd hello-world/
cmake .
make
# The project will build successfully
make clean
# git.h is deleted, but git-state-hash remains
make
# git-state-hash is present and up to date, but git.h does not regenerate
# Build fails with missing header
```

Can the build be configured such that if generated header is missing, it will be generated in all cases?
Less sure if this makes sense or not, but it might also be a good idea for `make clean` to remove git-state-hash.

**Comment by andrew-hardin** [comment] 2020-02-04 04:11
Thanks for the feedback. I merged two pull requests to address the issues you described:

- When `make clean` is executed, both the configured header and the git state file are removed (if `cmake >= 3.13.0`). This sets the project up to regenerate both files the next time `make` is executed.

- If the configured header somehow manages to goes missing, it'll automatically be regenerated.

Would you mind pulling a new copy of `master` and verifying that the issue is resolved? I wrote a copule of tests, but I may not have captured the behavior you described...

**Comment by jakebott** [comment] 2020-02-04 04:56
I can confirm that both issues are resolved.

Thanks for the quick response!

**Closed** 2020-04-04 01:16 UTC
